services:
  webponpes:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:lts-alpine
    container_name: webponpes
    ports:
      - '3000:3000'
    command: sh -c "node --env-file=.env build/index.js"
    restart: unless-stopped
    networks:
      - webponpes_network

networks:
  webponpes_network:
    driver: bridge
